impact/impact/urls.py
from django.contrib import admin
from django.urls import path, include
from stance import views
from toc import views as toc_views

from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'approaches', views.ApproachViewSet)
router.register(r'orientations', views.NormativeOrientationViewSet)
router.register(r'projections',
                views.ProjectionViewSet,
                basename='projection')



urlpatterns = [
    path('api/', include(router.urls)),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path(
        r'reference-autocomplete/',
        views.ReferenceAutocomplete.as_view(),
        name='reference-autocomplete'),
    path(
        r'approach-autocomplete/',
        views.ApproachAutocomplete.as_view(),
        name='approach-autocomplete'),

    path('assay/',
         views.AssayView.as_view(),
         name='assay'),

    path('approaches/',
         views.ApproachListView.as_view(),
         name='approach_list'),

    path('approaches/pdf/',
         views.buildPDF,
         name='approachespdf'),

    path('approaches/odt/',
         views.buildODT,
         name='approachesodt'),

    path('toc/digraph/',
         toc_views.toc_digraph_view,
         name='toc_digraph'),

    path('stance/pc/',
         views.stance_pc,
         name='stance_pc'),

    path('stance/projection/<int:ox_id>/<int:oy_id>/',
         views.ProjectionView.as_view(),
         name='projection'),
    
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

impact/stance/models.py
from django.db import models
from django.contrib.auth.models import User, Group
from django.utils.translation import gettext_lazy as _

from django.contrib.contenttypes.fields import GenericRelation
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models
from countries_plus.models import Country


class TaggedItem(models.Model):
    tag = models.SlugField()
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, related_name='types')
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    def __str__(self):
        return self.tag


class Reference(models.Model):
    title = models.CharField(max_length=255,
                             verbose_name=_("title"),
                             help_text=_("title"))
    citation = models.TextField(verbose_name=_("citation"),
                                   help_text=_("citation, APA style"))

    bibtex = models.TextField(null=True, blank=True)

    url = models.URLField(null=True, blank=True,
                          help_text=_('preferably DOI but others are fine if not available'))

    year = models.IntegerField(default=1900,
                               help_text=_('year of publication'))

    tags = GenericRelation(TaggedItem,
                           related_query_name='reference')

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title



class Approach(models.Model):
    title = models.CharField(max_length=255,
                             verbose_name=_("title"),
                             help_text=_("title"))
    description = models.TextField(verbose_name=_("description"),
                                   help_text=_("description"))

    discourse = models.TextField(verbose_name=_("socio-political discourse"),
                                 help_text=_("socio-political discourse"),
                                 null=True, blank=True,                                 
                                 default="")

    strong = models. BooleanField(default=False,
                                  help_text=_('Is this approach soft or strong?'))

    bibliography = models.ManyToManyField(Reference, blank=True)

    year_start = models.IntegerField(help_text="Start year", default=1900)
    year_end = models.IntegerField(help_text="End year", null=True, blank=True)

    
    country = models.ForeignKey(Country, on_delete=models.CASCADE)

    founder = models.CharField(max_length=255,
                               help_text=_("The person or comunity that started this approach"),
                               null=True, blank=True)
                               

    tags = GenericRelation(TaggedItem,
                           related_query_name='approach')

    proponent = models.ForeignKey(User,
                                  on_delete=models.CASCADE,
                                  verbose_name=_("proponent"),
                                  related_name=_('proposed'),
                                  help_text=_("person that submits an approach for our platform"))

    reviewer = models.ForeignKey(User,
                                 on_delete=models.CASCADE,
                                 null=True, blank=True,                                 
                                 verbose_name=_("reviewer"),
                                 help_text=_("person that reviews a proposed approach"))

    status = models.CharField(
        max_length=2,
        default='p',
        choices=(
            ('p', 'p'),  # proposal
            ('v', 'v'),  # validated
            ('r', 'r'),  # rejected
        ))


    class Meta:
        verbose_name_plural = "Approaches"

    def __str__(self):
        return self.title


class Reagent(models.Model):
    assertion = models.TextField(verbose_name=_("assertion"),
                                 help_text=_("description"))

    negative = models. BooleanField(default=False,
                                    help_text=_('reactions against this reagent should be interpreted as supportive of approach'))

    approach = models.ForeignKey(Approach,
                                 on_delete=models.CASCADE,
                                 verbose_name=_("approach"),
                                 help_text=_("approach"))

    tags = GenericRelation(TaggedItem,
                           related_query_name='reagent')

    def __str__(self):
        return self.assertion




class Assay(models.Model):
    reagent = models.ForeignKey(Reagent,
                                on_delete=models.CASCADE)
    reaction = models.SmallIntegerField(default=0,
                                        verbose_name=_("reaction"),
                                        help_text=_("reaction"))
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE)


    class Meta:
        unique_together = ('reagent', 'user')


class NormativeOrientation(models.Model):
    """
    the ascertainment of one's true position, as in a novel situation,
    with respect to attitudes, judgments, etc.
    """
    title = models.CharField(max_length=255,
                             verbose_name=_("title"),
                             help_text=_("title"))

    pole1 = models.CharField(max_length=255,
                             verbose_name=_("pole 1"),
                             help_text=_("one extreme"))
    pole2 = models.CharField(max_length=255,
                             verbose_name=_("pole 2"),
                             help_text=_("the other extreme"))


    description = models.TextField(verbose_name=_("description"),
                                   help_text=_("description"))
    bibliography = models.ManyToManyField(Reference, blank=True)

    def __str__(self):
        return self.title



class Projection(models.Model):
    approach = models.ForeignKey(Approach, on_delete=models.CASCADE)
    orientation = models.ForeignKey(NormativeOrientation,
                                              on_delete=models.CASCADE)
    magnitude = models.DecimalField(verbose_name=_("magnitude"),
                                    help_text=_("value [-1,1] that represents the projection of a dimension on an approach"),
                                    max_digits=4,
                                    decimal_places=3)

    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               verbose_name=_("author"),
                               help_text=_("author"))

    # TODO: llave triple para que no haya magnitudes duplicadas en tuplas de approach-orientation

    def __str__(self):
        return "%s %s" % (self.approach,
                          self.orientation)

impact/stance/forms.py
from dal import autocomplete
from django import forms
from stance import models
from django.forms import HiddenInput


class ApproachForm(forms.ModelForm):

    class Meta:
        model = models.Approach
        fields = ('__all__')
        widgets = {
            'bibliography': autocomplete.ModelSelect2Multiple(url='reference-autocomplete')
        }



class ReagentForm(forms.ModelForm):

    class Meta:
        model = models.Reagent
        fields = ('__all__')
        widgets = {
            'approach': autocomplete.ModelSelect2(url='approach-autocomplete')
        }



class ProjectionForm(forms.ModelForm):

    class Meta:
        model = models.Projection
        fields = ('approach', 'orientation', 'magnitude')
        widgets = {
            'approach': autocomplete.ModelSelect2(url='approach-autocomplete')
        }



class AssayForm(forms.Form):

    reaction = forms.IntegerField(widget=HiddenInput(),
                                  min_value=-2,
                                  max_value=2)

    reagent_id = forms.IntegerField(widget=HiddenInput())

impact/stance/views.py
from django.shortcuts import render
from dal import autocomplete
from stance import models
from django.views import View
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
import random
from stance import forms
from django.views import generic
from django.template.loader import render_to_string

import tempfile
import codecs
import subprocess
from time import sleep
from os import path, chdir
from django.http import HttpResponse

import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg
from pandas.plotting import parallel_coordinates

from stance.wrangle import assay_df

from rest_framework import viewsets
from rest_framework import permissions
from stance import serializers
from django.conf import settings
from pathlib import Path
import pypandoc


class ReferenceAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return models.Reference.objects.none()

        qs = models.Reference.objects.all()

        if self.q:
            qs = qs.filter(title__istartswith=self.q)

        return qs




class ApproachAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return models.Approach.objects.none()

        qs = models.Approach.objects.all()

        if self.q:
            qs = qs.filter(title__istartswith=self.q)

        return qs



class AssayView(View):
    form_class = forms.AssayForm
    template_name = 'stance/random_assay.html'

    def get(self, request, *args, **kwargs):
        all = set(models.Reagent.objects.all())
        answered = set([a.reagent for a in
                        models.Assay.objects.filter(user=request.user)])
        unanswered = list(all - answered)

        if unanswered:
            reagent = random.choice(unanswered)
            form = self.form_class(initial={'reagent_id': reagent.id})
            return render(request,
                          self.template_name,
                          {'reagent': reagent,
                           'form': form})
        else:
            return HttpResponseRedirect('/admin/stance/assay/')


    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            models.Assay(
                reagent=models.Reagent.objects.get(pk=request.POST['reagent_id']),
                reaction=request.POST['reaction'],
                user=self.request.user).save()



        return HttpResponseRedirect(reverse('assay'))



class ApproachListView(generic.ListView):
    model = models.Approach

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['approach_list'] = models.Approach.objects.all()
        context['reagent_list'] = models.Reagent.objects.all()

        return context



def buildPDF(request):

    module_dir = path.dirname(__file__)

    tex_path = path.join(module_dir, 'pdfs', 'approaches.tex')
    with codecs.open (tex_path, "w", "utf-8") as tex_file:
        output = render_to_string('stance/approaches.tex',
                                  {'approach_list' : models.Approach.objects.all()})
        tex_file.write(output)

    sleep(1)
    chdir(path.join(module_dir, 'pdfs'))
    subprocess.run(["xelatex", "-interaction=nonstopmode", tex_path],
                   stdin=subprocess.DEVNULL,
                   stdout=subprocess.DEVNULL,
                   stderr=subprocess.DEVNULL)

    pdf_path = tex_path.replace(".tex",".pdf")

    with open(pdf_path, 'rb') as pdf:
        response = HttpResponse(pdf.read(),content_type='application/pdf')
        response['Content-Disposition'] = 'filename=approaches.pdf'
        return response

def buildODT(request):

    outdir = Path(settings.MEDIA_ROOT).joinpath("odt")
    outdir.mkdir(exist_ok=True, parents=True)
    
    
    md_path = outdir.joinpath("approaches.md")


    with open(md_path, "w") as md_file:
        output = render_to_string('stance/approaches.md',
                                  {'approach_list' : models.Approach.objects.all()})
        md_file.write(output)


    odt_path = outdir.joinpath("approaches.odt")
    pypandoc.convert_file(str(md_path), 'odt', outputfile=str(odt_path))


    with open(odt_path, 'rb') as odt:
        response = HttpResponse(odt.read(),content_type='application/odt')
        response['Content-Disposition'] = 'filename=approaches.odt'
        return response


def stance_pc(request):

    df = assay_df(models.Assay.objects.all())

    fig, ax = plt.subplots()
    parallel_coordinates(df, 'user', ax=ax)
    plt.xticks(rotation=90)
    fig.tight_layout()
    
    response = HttpResponse(content_type = 'image/png')
    canvas = FigureCanvasAgg(fig)
    canvas.print_png(response)
    return response




class ProjectionView(View):
    form_class = forms.AssayForm
    template_name = 'stance/projection.html'
    
    def get(self, request, *args, **kwargs):
        
        ox = models.NormativeOrientation.objects.get(pk=kwargs['ox_id'])
        oy = models.NormativeOrientation.objects.get(pk=kwargs['oy_id'])
        
        return render(request,
                      self.template_name,
                      {'ox': ox,
                       'oy': oy}
                      )




class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = models.User.objects.all().order_by('-date_joined')
    serializer_class = serializers.UserSerializer
    permission_classes = [permissions.IsAuthenticated]


class ApproachViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = models.Approach.objects.all()
    serializer_class = serializers.ApproachSerializer
    permission_classes = [permissions.IsAuthenticated]
    

class NormativeOrientationViewSet(viewsets.ModelViewSet):
    queryset = models.NormativeOrientation.objects.all()
    serializer_class = serializers.NormativeOrientationSerializer
    permission_classes = [permissions.IsAuthenticated]


class ProjectionViewSet(viewsets.ModelViewSet):
    serializer_class = serializers.ProjectionSerializser
    permission_classes = [permissions.IsAuthenticated]

    def get_queryset(self):
        return models.Projection.objects.filter(author=self.request.user)

impact/stance/templates/stance/approach_list.html
{% extends "base.html" %}
{% load markdownify %}



{% block body %}
Approach List
<a class="rounded bg-white-300 p-1 m-1 hover:bg-gray-300"
   href="{% url 'approachespdf' %}">PDF</a>

{% if approach_list %}
<ul>
  {% for approach in approach_list %}
  <li>
    <div class="prose">
      <center>
	<h1>
	  <a
	    class="rounded bg-white-300 p-1 m-1 hover:bg-gray-300"
	    href="{% url 'admin:stance_approach_change' approach.id %}">
	    {{ approach.title }} </a> </h1>
      </center>
            
      {{ approach.description|markdownify }}
      
      <b>Bibliografía:</b>

      {% for bib in approach.bibliography.all %}
      <p>
	<a
	  class="rounded bg-white-300 p-1 m-1 hover:bg-gray-300"
	  href="{% url 'admin:stance_reference_change' bib.id %}">
	  {{ bib.citation }}
	</a>
      </p>
      {% endfor %}

      
      <b>Afirmaciones:</b>
      {% for reagent in approach.reagent_set.all %}
      {% if not reagent.negative  %} 
      <p>
	<a class="rounded bg-white-300 p-1 m-1 hover:bg-green-300"
	   href="{% url 'admin:stance_reagent_change' reagent.id %}">
	  {{ reagent.assertion }}
	</a>
      </p>
      {% endif %}
      {% endfor %}

      <b>Negaciones:</b>
      {% for reagent in approach.reagent_set.all %}
      {% if reagent.negative  %} 
      <p>
	<a
	  class="rounded bg-white-300 p-1 m-1 hover:bg-red-300"
	  href="{% url 'admin:stance_reagent_change' reagent.id %}">
	  {{ reagent.assertion }}
	</a>
      </p>
      {% endif %}
      {% endfor %}
    </div>

  </li>
  {% endfor %}
</ul>

<a class="rounded bg-white-300 p-1 m-1 hover:bg-gray-300"
   href="{% url 'approachespdf' %}">
  PDF</a>

{% else %}
<p>There are no approaches in the library.</p>
{% endif %}
{% endblock %}

impact/stance/templates/stance/assay_form.html
{% extends 'base.html' %}

{% block body %}
<div class="bg-gray-100 m-4 p-4 rounded-md">

  <div class="m-4 w-1/2">
  {{ reagent.assertion }}
  </div>

  <form method="post">{% csrf_token %}
    <table class="form-group">
      {{ form.as_table }}
    </table>

    <input
      type="submit"
      value="react"
      class="rounded-md bg-blue-500 hover:bg-green-500 text-white p-4 transition">





</form>
</div>


{% endblock %}

impact/stance/templates/stance/projection.html
{% extends "base.html" %}
{% load static %}


{% block extrahead %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/paper.js/0.12.15/paper-full.js" integrity="sha512-XV5MGZ7Tv+G60rzU8P7tPUlaf0yz7SJ/uI9CLAwyLcZKl9kzxJQFs3nsBNZVNVAwNOkBLqrzMvjGMEycDccqiA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://cdn.jsdelivr.net/npm/js-cookie@3.0.1/dist/js.cookie.min.js" integrity="sha256-0H3Nuz3aug3afVbUlsu12Puxva3CP4EhJtPExqs54Vg=" crossorigin="anonymous"></script>



<style>
  html,
  body {
      height: 100%;
  }


  .paperscript .canvas canvas {
      width:40%;
      height:80%;
      float:left;
      margin: 10px;
  }

  div{
      border-radius: 5px;
  }

  .l{
      width:180px;
      height:80%;
      float:left;
      margin: 10px;
  }
  .draggable-list li{
    display: flex;
    flex: 1;
  }
  .draggable-list number{
    display: flex;
    align-self: center;
  }
  .over{
    background-color: rgb(176, 176, 176);
    
  }
  .aproach{
    background-color: rgb(208, 208, 208);
  }
  .number{
    margin-left: 30px;
    margin-right: 30px;
  }
</style>

{% endblock %}


{% block body %}
<div class="flex flex-row bg-gray-300">
  <div id="leyenda" class="m-2 p-2 flex flex-col bg-slate-300">
    <div id="approaches_div" class="max-w-sm rounded overflow-hidden shadow-lg">
    
    </div>
    <div id="controls_div" class="max-w-sm rounded overflow-hidden shadow-lg">
    
    </div>
    
    <ul class="draggable-list" id="draggable-list"></ul>
    
  </div>

  <div class="">
    <canvas id="canvas" style="user-select: none;" width="805" height="805"></canvas>
  </div>
</div>



<script type="text/javascript">
  // Only executed our code once the DOM is ready.
//  window.onload = function() {
//  }
  var ox_id = "{{ ox.id }}";
  var oy_id = "{{ oy.id }}";
</script>

<script type="text/javascript"
	src="{% static 'src/aguas.js' %}"
	defer></script>


{% endblock %}

impact/stance/templates/stance/random_assay.html
{% extends 'base.html' %}

{% block body %}
<div class="bg-gray-100 m-4 p-4 rounded-md">

  <div class="m-4 w-1/2">
  {{ reagent.assertion }}
  </div>

  <form id="assay_form" method="post">{% csrf_token %}
    <table class="form-group">
      {{ form.as_table }}
    </table>

    <input
      type="button"
      value="strongly disagree"
      onClick="react(-2)"
      class="rounded-md bg-red-800 hover:bg-red-500 text-white p-4 transition">

    <input
      type="button"
      value="disagree"
      onClick="react(-1)"
      class="rounded-md bg-red-600 hover:bg-red-500 text-white p-4 transition">

    <input
      type="button"
      value="do not agree nor disagree"
      onClick="react(0)"
      class="rounded-md bg-gray-200 hover:bg-blue-200 text-gray-600 p-4 transition">

    <input
      type="button"
      value="agree"
      onClick="react(1)"
      class="rounded-md bg-green-600 hover:bg-green-500 text-white p-4 transition">

    <input
      type="button"
      value="strongly agree"
      onClick="react(2)"
      class="rounded-md bg-green-900 hover:bg-green-500 text-white p-4 transition">


  </form>
</div>


<script>
  function react(n){
      document.getElementById("id_reaction").value = n;
      document.getElementById("assay_form").submit()
  }
</script>

{% endblock %}